-define(INTEGER, {terl_type, integer}).
-define(FLOAT, {terl_type, float}).
-define(BOOLEAN, {terl_type, boolean}).
-define(STRING, {terl_type, string}).
-define(INVALID, type_internal:invalid_operator()).
-define(UNDEFINED, undefined).
